feat(17781): Notification framework and new release notice
hivemq/hivemq-edge pull request #205
Opened 2023-11-22 15:26 UTC by vanch3d

See https://hivemq.kanbanize.com/ctrl_board/57/cards/17781/details/

This PR introduces notice to the user for any new release of the system, for potential updating it.

The feature is introduced as part of the wider management of notifications in HiveMQ Edge. 

### Design
- a simple "notification" button badge is added to the navigation panel, making the feature available from every point of the web ap[plication
- The widget contains a small badge indicating the number of unread notifications 
- The notifications are fetched dynamically; therefore the number displayed can change at any point in time.
- If there is no unread notifications, the button basge is inactive
- When the user clicks on the button badge, the unread notifications are displayed as "toasts" on the right-hand side of the screen, consistent with any other toasts used in the web app.
- The design of the toasts are slightly different: light version, info or warning only, a "do not notify me again" check box, a longer timeout. 
- Once displayed and then closed (manually or timed out), the notification will be considered as "unread", the button basge being adapted accordingly
- The "unread" status is NOT persisted: reloading the page will renew the notification
- Checking the "do not notify me again" option WILL persist the decision: the same notification (as identified by its name/id, will not be listed again

### Out-of-scope
- The notifications will be limited to 9 (single digit badge on the button). This might create a discrepency.
- There is no mechanism in the UI (short of deleting the `localStorage`) to cancel the "Do not notify me again". A user preference or settings might have to be implemented
- The use of toast for the notifications has the merit of consistency within the app but might create a visual overload when combined with other "overlay" components (other toasts or panels, see last screenshot below). This will have to be monitored, using `Heap Analytics` for user journeys monitoring

### After

2023-11-23 20:45 UTC, vanch3d commented
Holding on this PR, until I can assess pros/cons of delivering a feature like notifications without persistency

2023-11-30 16:36 UTC, vanch3d commented
> Holding on this PR, until I can assess pros/cons of delivering a feature like notifications without persistency

Good to go with the current UX:
- fix the version check
- add localStorage for the "Do not notify me again"

2023-12-05 10:56 UTC, simon622 requested changes
Looks nice. The notifications disappear as I consume them. Question, what generates the new version available notification? Doesn't seem to come from the API?

The UI works nicely, I wonder if we could use a Bell icon (typically used for notifications) rather than an email icon?

Other than that, work beautifully.

2023-12-05 12:20 UTC, vanch3d commented
> Looks nice. The notifications disappear as I consume them. Question, what generates the new version available notification? Doesn't seem to come from the API?

The version request is done from the UI, using GitHub public API. It might be worth integrating it with the backend's existing check and notifications.

2023-12-05 12:44 UTC, vanch3d commented
> The UI works nicely, I wonder if we could use a Bell icon (typically used for notifications) rather than an email icon?

Done


![Screenshot 2023-12-05 at 12 43 21](https://github.com/hivemq/hivemq-edge/assets/2743481/b36cd341-39a4-4b5a-a399-538851674a21)

2023-12-06 09:12 UTC, simon622 approved these changes
love the new icon!

2023-12-06 09:51 UTC, merged