[Bi-Directional, OPC UA, HTTP] backend implementation
hivemq/hivemq-edge pull request #572
Opened 2024-09-26 14:23 UTC by Florian-Limpoeck

2024-09-27 09:51 UTC, DC2-DanielKrueger commented on hivemq-edge/src/main/java/com/hivemq/protocols/ProtocolAdapterWrapper.java
> -public class ProtocolAdapterWrapper<T extends ProtocolAdapter> implements ProtocolAdapter {
nice, was a big mistake to make it an ProtocolAdapter. Was easy at the time, but super error prone

2024-09-27 13:34 UTC, codepitbull requested changes
Tests broken

2024-09-27 14:18 UTC, Florian-Limpoeck commented on hivemq-edge/src/test/java/com/hivemq/protocols/ProtocolAdapterManagerTest.java
> +                protocolAdapterWrapper.getProtocolAdapterMetricsService())).thenReturn(CompletableFuture.completedFuture(null));
yeah it doesnt even compile, was a refactoring miss

2024-09-27 15:19 UTC, codepitbull approved these changes

2024-09-30 05:55 UTC, DC2-DanielKrueger approved these changes

2024-10-02 05:45 UTC, DC2-DanielKrueger commented on modules/hivemq-edge-module-file/src/main/java/com/hivemq/edge/adapters/file/FileProtocolAdapterInformation.java
>      public @NotNull String getProtocolId() {
that breaks old configs as the protocol id is used in the config tag IIRC

2024-10-02 12:24 UTC, merged